# Numpy

#### 1.Создать вектор (одномерный массив) размера 100, заполненный нулями

In [7]:
import numpy as np
Z = np.zeros((100,))
print(Z)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0.]


#### 2.Создать вектор размера 100, заполненный единицами

In [8]:
import numpy as np
Z = np.ones((100,))
print(Z)

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1.]


#### 3.Создать вектор размера 100, заполненный числом 3

In [15]:
import numpy as np
c = np.full((100,), 3)  
print(c)   

[3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3
 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3
 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3]


#### 4. Как получить документацию о функции numpy.add из командной строки?

In [1]:
import numpy as np
help(np.add)

Help on ufunc object:

add = class ufunc(builtins.object)
 |  Functions that operate element by element on whole arrays.
 |  
 |  To see the documentation for a specific ufunc, use `info`.  For
 |  example, ``np.info(np.sin)``.  Because ufuncs are written in C
 |  (for speed) and linked into Python with NumPy's ufunc facility,
 |  Python's help() function finds this page whenever help() is called
 |  on a ufunc.
 |  
 |  A detailed explanation of ufuncs can be found in the docs for :ref:`ufuncs`.
 |  
 |  Calling ufuncs:
 |  ===============
 |  
 |  op(*x[, out], where=True, **kwargs)
 |  Apply `op` to the arguments `*x` elementwise, broadcasting the arguments.
 |  
 |  The broadcasting rules are:
 |  
 |  * Dimensions of length 1 may be prepended to either array.
 |  * Arrays may be repeated along dimensions of length 1.
 |  
 |  Parameters
 |  ----------
 |  *x : array_like
 |      Input arrays.
 |  out : ndarray, None, or tuple of ndarray and None, optional
 |      Alternate array o

#### 5. Поменять 2 строки в матрице

In [2]:
matrix = [[1,2,3,],[4,5,6],[7,8,9],[3,4,5,]]
matrix[1], matrix[2]=matrix[2],matrix[1]
matrix

[[1, 2, 3], [7, 8, 9], [4, 5, 6], [3, 4, 5]]

import numpy as np
 

#### 6. Создать вектор со значениями от 10 до 100

In [18]:
import numpy as np
Z = np.arange(10,100)
print(Z)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50 51 52 53 54 55 56 57
 58 59 60 61 62 63 64 65 66 67 68 69 70 71 72 73 74 75 76 77 78 79 80 81
 82 83 84 85 86 87 88 89 90 91 92 93 94 95 96 97 98 99]


#### 7. Развернуть вектор (первый становится последним)

In [21]:
import numpy as np
Z = np.arange(50)
Z = Z[::-1]
print(Z)

[49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26
 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10  9  8  7  6  5  4  3  2
  1  0]


#### 8. Создать матрицу (двумерный массив) 4x4 со значениями от 0 до 16

In [4]:
import numpy as np
Z = np.arange(16).reshape(4,4)
print (Z)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]


#### 9.  Дан вектор [1, 2, 3, 4, 5], построить новый вектор с тремя нулями между каждым значением

#### 10. Создать 3x3 единичную матрицу

In [8]:
import numpy as np
Z = np.eye(3)
print(Z)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


#### 11. Создать массив 3x3x3 со случайными значениями

In [9]:
import numpy as np
Z = np.random.random((3,3,3))
print(Z)

[[[0.6697071  0.26210393 0.36347344]
  [0.90943501 0.14413628 0.43071098]
  [0.10383419 0.54571697 0.3432633 ]]

 [[0.18697156 0.06009042 0.96961201]
  [0.73537787 0.29464367 0.85469603]
  [0.25947634 0.19912616 0.1257369 ]]

 [[0.93437255 0.55030079 0.30795334]
  [0.4141235  0.15978107 0.88322777]
  [0.66751528 0.48905041 0.12385653]]]


#### 12. Создать массив 10x10 со случайными значениями, найти минимум и максимум

In [11]:
import numpy as np
Z = np.random.random((10,10))
Zmin, Zmax = Z.min(), Z.max()
print(Z)
print(Zmin, Zmax)

[[0.80259526 0.89420146 0.67536603 0.91487474 0.41228212 0.09100656
  0.96878733 0.55112597 0.3863891  0.69722736]
 [0.28959366 0.33565766 0.94042449 0.52405864 0.67079791 0.08526742
  0.43292028 0.68109632 0.61645756 0.15995605]
 [0.1008645  0.8141479  0.21653923 0.65410217 0.3479264  0.90808952
  0.22376231 0.64367957 0.50328485 0.53599704]
 [0.32304343 0.96279636 0.09670052 0.20020786 0.42927057 0.19430372
  0.88125338 0.90269629 0.26565207 0.95372552]
 [0.02930144 0.70965099 0.95679635 0.01138729 0.80002462 0.82961232
  0.45945099 0.92283711 0.46777523 0.7394917 ]
 [0.90586777 0.81979411 0.79683989 0.96254826 0.82617831 0.9562031
  0.73631998 0.05020133 0.80238153 0.05650455]
 [0.23055004 0.10642229 0.30683388 0.44702023 0.68688461 0.24970101
  0.97541236 0.92301884 0.14253656 0.87055687]
 [0.67164872 0.33745732 0.48956427 0.27975968 0.63294475 0.97186766
  0.239855   0.0942687  0.67802558 0.74804554]
 [0.7106151  0.63627707 0.11765334 0.56388178 0.55574447 0.20765949
  0.69390584 

#### 13. Создать случайный вектор размера 30 и найти среднее значение всех элементов

In [13]:
import numpy as np
Z = np.random.random(30)
m = Z.mean()
print(m)

0.6441154686920636


#### 14. Создать матрицу с 0 внутри, и 1 на границах

In [15]:
import numpy as np
Z = np.ones((10,10))
Z[1:-1,1:-1] = 0
print(Z)

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


#### 15. Удивите меня в этом задании, покажите какое нибудь класное преобразование в numpy (не идет в зачет)

In [16]:
import numpy as np
Z = np.zeros((100,))
print(Z)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0.]


#### 16. Создать 5x5 матрицу с 1,2,2,4 под диагональю

In [17]:
import numpy as np
Z = np.diag(np.arange(1, 5), k=-1)
print(Z)

[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


#### 17. Создать 8x8 матрицу и заполнить её в шахматном порядке

In [18]:
import numpy as np
Z = np.zeros((8,8), dtype=int)
Z[1::2,::2] = 1
Z[::2,1::2] = 1
print(Z)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


#### 18. Дан массив размерности (6,7,8). Каков индекс (x,y,z) сотого элемента?

In [19]:
import numpy as np
print(np.unravel_index(100, (6,7,8)))


(1, 5, 4)


#### 19. Создать 8x8 матрицу и заполнить её в шахматном порядке, используя функцию tile

In [20]:
import numpy as np
Z = np.tile(np.array([[0,1],[1,0]]), (4,4))
print(Z)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


#### 20. Перемножить матрицы 5x3 и 3x2

In [21]:
import numpy as np
Z = np.dot(np.ones((5,3)), np.ones((3,2)))
print(Z)

[[3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]]


#### 21. Дан массив, поменять знак у элементов, значения которых между 3 и 8

In [22]:
import numpy as np
Z = np.arange(15)
Z[(3 < Z) & (Z <= 8)] *= -1
print(Z)

[ 0  1  2  3 -4 -5 -6 -7 -8  9 10 11 12 13 14]


#### 23. Создать 5x5 матрицу со значениями в строках от 0 до 4

In [23]:
import numpy as np
Z = np.zeros((5,5))
Z += np.arange(5)
print(Z)

[[0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]]


#### 24. Есть генератор, сделать с его помощью массив

#### 25. Создать вектор размера 10 со значениями от 0 до 1, не включая ни то, ни другое

In [25]:
import numpy as np
Z = np.linspace(0,1,12)[1:-1]
print(Z)

[0.09090909 0.18181818 0.27272727 0.36363636 0.45454545 0.54545455
 0.63636364 0.72727273 0.81818182 0.90909091]


#### 26. Отсортировать вектор

In [26]:
import numpy as np
Z = np.random.random(10)
Z.sort()
print(Z)

[0.06560334 0.15098541 0.19016741 0.20141455 0.20430898 0.34037409
 0.63467037 0.87389322 0.87814526 0.89249038]


#### 27. Проверить, одинаковы ли 2 numpy массива

In [68]:
import numpy as np
A = np.random.randint(0,2,5)
B = np.random.randint(0,2,5)
equal = np.allclose(A,B)
print(equal)
print(A)
print(B)

True
[0 0 0 0 1]
[0 0 0 0 1]


#### 28. Сделать массив неизменяемым

In [71]:
import numpy as np
Z = np.zeros(10)
Z.flags.writeable = False
Z[0] = 1
print(Z)

ValueError: assignment destination is read-only

#### 29. Найти n наибольших значений в массиве

In [72]:
import numpy as np
Z = np.arange(10000)
np.random.shuffle(Z)
n = 5
print (Z[np.argpartition(-Z,n)[:n]])

[9995 9999 9998 9997 9996]


#### 30. Заменить максимальный элемент на ноль

In [73]:
import numpy as np
Z = np.random.random(10)
Z[Z.argmax()] = 0
print(Z)

[0.         0.16123553 0.44817467 0.86205793 0.67553612 0.67745615
 0.69893133 0.73033586 0.86132197 0.12434193]


#### 31. Создать структурированный массив с координатами x, y на сетке в квадрате [0,1]x[0,1]

In [74]:
import numpy as np
Z = np.zeros((10,10), [('x',float),('y',float)])
Z['x'], Z['y'] = np.meshgrid(np.linspace(0,1,10),
                             np.linspace(0,1,10))
print(Z)

[[(0.        , 0.        ) (0.11111111, 0.        )
  (0.22222222, 0.        ) (0.33333333, 0.        )
  (0.44444444, 0.        ) (0.55555556, 0.        )
  (0.66666667, 0.        ) (0.77777778, 0.        )
  (0.88888889, 0.        ) (1.        , 0.        )]
 [(0.        , 0.11111111) (0.11111111, 0.11111111)
  (0.22222222, 0.11111111) (0.33333333, 0.11111111)
  (0.44444444, 0.11111111) (0.55555556, 0.11111111)
  (0.66666667, 0.11111111) (0.77777778, 0.11111111)
  (0.88888889, 0.11111111) (1.        , 0.11111111)]
 [(0.        , 0.22222222) (0.11111111, 0.22222222)
  (0.22222222, 0.22222222) (0.33333333, 0.22222222)
  (0.44444444, 0.22222222) (0.55555556, 0.22222222)
  (0.66666667, 0.22222222) (0.77777778, 0.22222222)
  (0.88888889, 0.22222222) (1.        , 0.22222222)]
 [(0.        , 0.33333333) (0.11111111, 0.33333333)
  (0.22222222, 0.33333333) (0.33333333, 0.33333333)
  (0.44444444, 0.33333333) (0.55555556, 0.33333333)
  (0.66666667, 0.33333333) (0.77777778, 0.33333333)
  (0.8888

#### 32. Из двух массивов сделать матрицу Коши C (Cij = 1/(xi - yj))

In [75]:
import numpy as np
X = np.arange(8)
Y = X + 0.5
C = 1.0 / np.subtract.outer(X, Y)
print(np.linalg.det(C))

3638.1636371179666


#### 33. Найти минимальное и максимальное значение, принимаемое каждым числовым типом numpy

In [76]:
import numpy as np
for dtype in [np.int8, np.int32, np.int64]:
   print(np.iinfo(dtype).min)
   print(np.iinfo(dtype).max)
for dtype in [np.float32, np.float64]:
   print(np.finfo(dtype).min)
   print(np.finfo(dtype).max)
   print(np.finfo(dtype).eps)

-128
127
-2147483648
2147483647
-9223372036854775808
9223372036854775807
-3.4028235e+38
3.4028235e+38
1.1920929e-07
-1.7976931348623157e+308
1.7976931348623157e+308
2.220446049250313e-16


#### 34. Напечатать все значения в массиве

In [77]:
import numpy as np
np.set_printoptions(threshold=np.nan)
Z = np.zeros((25,25))
print(Z)

ValueError: threshold must be numeric and non-NAN, try sys.maxsize for untruncated representation

#### 35. Найти ближайшее к заданному значению число в заданном массиве

In [78]:
import numpy as np
Z = np.arange(100)
v = np.random.uniform(0,100)
index = (np.abs(Z-v)).argmin()
print(Z[index])


0


#### 36. Преобразовать массив из float в int

In [83]:
import numpy as np
Z = np.arange(10, dtype=np.float32)
Z = Z.astype(np.int32, copy=False)
Z.dtype

dtype('int32')

#### 37. Каков эквивалент функции enumerate для numpy массивов?

In [84]:
import numpy as np
Z = np.arange(9).reshape(3,3)
for index, value in np.ndenumerate(Z):
    print(index, value)
for index in np.ndindex(Z.shape):
    print(index, Z[index])

(0, 0) 0
(0, 1) 1
(0, 2) 2
(1, 0) 3
(1, 1) 4
(1, 2) 5
(2, 0) 6
(2, 1) 7
(2, 2) 8
(0, 0) 0
(0, 1) 1
(0, 2) 2
(1, 0) 3
(1, 1) 4
(1, 2) 5
(2, 0) 6
(2, 1) 7
(2, 2) 8


#### 38. Случайно расположить p элементов в 2D массив

In [87]:
import numpy as np
n = 10
p = 7
Z = np.zeros((n,n))
np.put(Z, np.random.choice(range(n*n), p, replace=False), 1)
print(Z)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


#### 39. Отнять среднее из каждой строки в матрице

In [91]:
import numpy as np
X = np.random.rand(5, 10)
Y = X - X.mean(axis=1, keepdims=True)
print(Z)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


#### 40. Отсортировать матрицу по n-ому столбцу

In [92]:
import numpy as np
Z = np.random.randint(0,10,(3,3))
n = 1  # Нумерация с нуля
print(Z)
print(Z[Z[:,n].argsort()])

[[9 8 0]
 [2 0 4]
 [0 5 3]]
[[2 0 4]
 [0 5 3]
 [9 8 0]]


#### 41. Определить, есть ли в 2D массиве нулевые столбцы

In [93]:
import numpy as np
Z = np.random.randint(0,3,(3,10))
print((~Z.any(axis=0)).any())

False


#### 42. Дан массив, добавить 1 к каждому элементу с индексом, заданным в другом массиве (осторожно с повторами)

In [94]:
import numpy as np
Z = np.ones(10)
I = np.random.randint(0,len(Z),20)
Z += np.bincount(I, minlength=len(Z))
print(Z)

[2. 1. 5. 7. 4. 2. 2. 1. 3. 3.]


#### 43. Дан массив (w,h,3) (картинка) dtype=ubyte, посчитать количество различных цветов

In [95]:
import numpy as np
w,h = 16,16
I = np.random.randint(0, 2, (h,w,3)).astype(np.ubyte)
F = I[...,0] * 256 * 256 + I[...,1] * 256 + I[...,2]
n = len(np.unique(F))
print(np.unique(I))

[0 1]


#### 44. Дан четырехмерный массив, посчитать сумму по последним двум осям

In [ ]:
import numpy as np
A = np.random.randint(0,10, (3,4,3,4))
sum = A.reshape(A.shape[:-2] + (-1,)).sum(axis=-1)
print(sum)